name: 'Grafana E2E version resolver'
description: 'Resolve Grafana versions for use in E2E tests'

inputs:
  skip-grafana-dev-image:
    default: false
    required: false
    description: 'Optionally, you can skip the Grafana dev image'
    type: boolean
  version-resolver-type:
    required: true 
    type: choice
    default: plugin-grafana-dependency
    description: >
     Choose between different version resolver types.
      plugin-grafana-dependency: Resolve versions based on the Grafana version specified in the plugin.json file.
      version-support-policy: Resolve versions according to Grafana's plugin compatibility policy. I.e. the latest major version and the last minor of the previous major version.
    options: 
      - plugin-grafana-dependency
      - version-support-policy
  grafana-dependency:
    required: false
    description: 'Optionally, use this input to pass a semver range of supported Grafana versions to test against. This is only used when version-resolver-type is plugin-grafana-dependency. If not provided, the action will try to read grafanaDependency from the plugin.json file.'
    type: string
  limit:
    required: false
    description: 'The maximum number of versions to resolve. Default is 6, 0 means no limit.'
    default: "6"
  plugin-directory:
    required: false
    description: 'The directory where the plugin.json file is located. Default is `src`.'
    default: src

output:
  matrix:
    description: 'Versions to test against'

runs:
  using: node20
  main: ./dist/index.js
