name: "Grafana Bundle Types"
description: "Bundles a Grafana plugins types and pushes them to npm."

outputs:
  typesFilePath:
    description: "The path to the built types file."
    value: ${{ steps.set-outputs.outputs.typesFilePath }}

inputs:
  entryPoint:
    description: "Location of types file to bundle."
    required: false
    default: "./src/types/index.ts"
  tsConfig:
    description: "A path to the tsconfig file to use when bundling types."
    required: false
    default: ""
  outDir:
    description: "A directory to output the types file to. Defaults to ./dist."
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: "${{ inputs.node-version }}"

    - name: Install dependencies
      run: ${{ github.action_path }}/pm.sh install
      shell: bash

    - name: Bundle types
      run: npx -y @grafana/plugin-types-bundler@latest --entry-point ${{ inputs.entryPoint }}
      shell: bash

    - id: get-secrets
      uses: grafana/shared-workflows/actions/get-vault-secrets@main
      with:
        common_secrets: |
          GITHUB_APP_ID=plugins-platform-bot-app:app-id
          GITHUB_APP_PRIVATE_KEY=plugins-platform-bot-app:app-private-key

    - name: Generate token
      id: generate_token
      uses: tibdex/github-app-token@v2
      with:
        app_id: ${{ env.GITHUB_APP_ID }}
        private_key: ${{ env.GITHUB_APP_PRIVATE_KEY }}

    - name: Clone NPM package types package repo
      run: |
        cd ..
        gh auth status
      shell: bash
      env:
        GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
