name: Test Schema Types Action
on:
  workflow_dispatch:
  push:
    branches: [hugoh/adds-schema-types-bundling]

# These permissions are needed to assume roles from Github's OIDC.
permissions:
  contents: read
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./bundle-schema-types
        with:
          node-version: "24"
